### ISSUE TITLE
Set color

### ISSUE THREAD

**Issue by paskalll** [avpnusr/liquidctl-docker#2]
hey

just a question what about the set color attribute?
Like:
# liquidctl --match kraken set sync color fixed 0080ff
# liquidctl --match "smart device" set led color moving-alternating "hsv(30,98,100)" "hsv(30,98,10)" --speed slower

**Comment by avpnusr** [comment]
Hi @paskalll 

I tried to implement an option to do this - checkout the README, if this fits your needs ;)

Regards

**Comment by avpnusr** [comment]
I assume, the issue can be closed, as the option is implemented
